export interface TestingLab {
  id: string;
  name: string;
  city: string;
  state: string;
  address: string;
  phone: string;
  email: string;
  nablAccredited: boolean;
  bisRecognized: boolean;
  categories: string[];
  website?: string;
}

export const BIS_RECOGNIZED_LABS: TestingLab[] = [
  {
    id: 'lab-1',
    name: 'National Test House (NTH), Northern Region',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh (Delhi NCR)',
    address: 'Kamla Nehru Nagar, Ghaziabad, UP 201002',
    phone: '+91 120 2789941',
    email: 'nthnr-ca@nic.in',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Electrical & Appliances', 'LED & Lighting', 'Cement & Steel', 'Helmets & Fire Safety'],
    website: 'https://nth.gov.in',
  },
  {
    id: 'lab-2',
    name: 'ERTL (East) — Electronics Regional Test Laboratory',
    city: 'Kolkata',
    state: 'West Bengal',
    address: 'DN Block, Sector V, Salt Lake, Kolkata 700091',
    phone: '+91 33 23678500',
    email: 'ertleast@stqc.gov.in',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Electrical & Appliances', 'LED & Lighting', 'Batteries & IT'],
    website: 'https://stqc.gov.in',
  },
  {
    id: 'lab-3',
    name: 'SAMEER (Society for Applied Microwave Electronics)',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'IIT Campus, Powai, Mumbai 400076',
    phone: '+91 22 25723703',
    email: 'info@sameer.gov.in',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Batteries & IT', 'Electrical & Appliances', 'LED & Lighting'],
    website: 'https://sameer.gov.in',
  },
  {
    id: 'lab-4',
    name: 'TUV Rheinland India Pvt Ltd',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: 'Electronic City Phase 1, Doddathogur, Bengaluru 560100',
    phone: '+91 80 67243500',
    email: 'info@ind.tuv.com',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Electrical & Appliances', 'LED & Lighting', 'Batteries & IT', 'Toys'],
    website: 'https://www.tuv.com/india',
  },
  {
    id: 'lab-5',
    name: 'SGS India Private Limited',
    city: 'Gurugram',
    state: 'Haryana (Delhi NCR)',
    address: '28B, Udyog Vihar Phase IV, Gurugram 122015',
    phone: '+91 124 6787600',
    email: 'sgs.india@sgs.com',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Toys', 'Food & Water', 'Helmets & Fire Safety', 'Cement & Steel'],
    website: 'https://www.sgs.com/en-in',
  },
  {
    id: 'lab-6',
    name: 'Intertek India Private Limited',
    city: 'New Delhi',
    state: 'Delhi NCR',
    address: 'E-20, Block B-1, Mohan Cooperative Industrial Estate, New Delhi 110044',
    phone: '+91 11 41595400',
    email: 'info.india@intertek.com',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Electrical & Appliances', 'LED & Lighting', 'Toys', 'Batteries & IT'],
    website: 'https://www.intertek.com',
  },
  {
    id: 'lab-7',
    name: 'UL Solutions India',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: 'Kalyani Tech Park, Whitefield, Bengaluru 560066',
    phone: '+91 80 41384400',
    email: 'customerservice.in@ul.com',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Electrical & Appliances', 'LED & Lighting', 'Batteries & IT', 'Helmets & Fire Safety'],
    website: 'https://india.ul.com',
  },
  {
    id: 'lab-8',
    name: 'Central Power Research Institute (CPRI)',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: 'Prof. Sir C.V. Raman Road, Sadashivanagar, Bengaluru 560080',
    phone: '+91 80 22072002',
    email: 'cpri@cpri.in',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Electrical & Appliances', 'Cement & Steel'],
    website: 'https://cpri.res.in',
  },
  {
    id: 'lab-9',
    name: 'Eurofins Analytical Services India',
    city: 'Bengaluru',
    state: 'Karnataka',
    address: '#540/1, Doddanakundi Industrial Area 2, Hoodi, Bengaluru 560048',
    phone: '+91 80 30982500',
    email: 'infoindia@eurofins.com',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Food & Water', 'Toys'],
    website: 'https://www.eurofins.in',
  },
  {
    id: 'lab-10',
    name: 'Shriram Institute for Industrial Research',
    city: 'Delhi',
    state: 'Delhi NCR',
    address: '19, University Road, Delhi 110007',
    phone: '+91 11 27667983',
    email: 'sridlh@vsnl.com',
    nablAccredited: true,
    bisRecognized: true,
    categories: ['Toys', 'Food & Water', 'Cement & Steel', 'Electrical & Appliances'],
    website: 'http://www.shriraminstitute.org',
  },
];
